REM 'Using FUNCTION…END FUNTION, write a program to calculate the average of three numbers [SLC 2067] [SLC 2070 S]
DECLARE FUNCTION AVERAGE (A, B, C)
CLS
INPUT "ENTER FIRST NUMBER"; A
INPUT "ENTER SECOND NUMBER"; B
INPUT "ENTER THIRD NUMBER"; C
PRINT "AVERAGE OF THREE NUMBERS"; AVERAGE(A, B, C)
END

FUNCTION AVERAGE (A, B, C)
    AVERAGE = (A + B + C) / 3
END FUNCTION
