REM 'program using FUNCTION…END FUNCTION to find area of the triangle [SLC 2072] 
DECLARE FUNCTION AREA (B, H)
CLS
INPUT "ENTER BREADTH"; B
INPUT "ENTER HEIGHT"; H
AR = AREA(B, H)
PRINT "AREA OF TRIANGLE "; AR
END

FUNCTION AREA (B, H)
    A = 1 / 2 * (B * H)
    AREA = A
END FUNCTION
