REM 'program in QBASIC to find the total surface area of a box using FUNCTION….END FUNCTION. [SLC 2068 S] [TSA = 2(LB+LH+BH)
DECLARE FUNCTION TSAREA (L, B, H)
CLS
INPUT "ENTER LENGTH"; L
INPUT "ENTER BREADTH"; B
INPUT "ENTER HEIGHT"; H
PRINT "TOTAL SURFACE AREA OF CUBOID"; TSAREA(L, B, H)
END

FUNCTION TSAREA (L, B, H)
    TSAREA = 2 * (L * B + B * H + H * L)
END FUNCTION

