REM 'Using FUNCTION……END FUNCTION, write a program to calculate distance travelled by a body. (Hint: s=ut+ (1/2) at2)  [SLC 2065]
DECLARE FUNCTION DISTANCE (U, T, A)
CLS
INPUT "ENTER INITIAL VELOCITY"; U
INPUT "ENTER TIME"; T
INPUT "ENTER ACCELARATION"; A
PRINT "DISTANCE TRAVELLED = "; DISTANCE(U, T, A)
END

FUNCTION DISTANCE (U, T, A)
    DISTANCE = U * T + 1 / 2 * A * T ^ 2
END FUNCTION
