REM 'program in QBASIC to find square and cube of a given number using FUNCTION…..END FUNCTION
DECLARE FUNCTION SQUARE (N)
DECLARE FUNCTION CUBE (N)
CLS
INPUT "ENTER ANY NUMBER"; N
S = SQUARE(N)
C = CUBE(N)
PRINT "SQUARE OF NUMBER"; S
PRINT "CUBE OF NUMBER"; C
END

FUNCTION SQUARE (N)
    SQ = N ^ 2
    SQUARE = SQ
END FUNCTION

FUNCTION CUBE (N)
    CB = N ^ 3
    CUBE = CB
END FUNCTION
