REM 'cube root of a given number using FUNCTION…..END FUNCTION
DECLARE FUNCTION CBROOT (N)
CLS
INPUT "ENTER ANY NUMBER"; N
C = CBROOT(N)
PRINT "CUBE ROOT OF NUMBER"; C
END

FUNCTION CBROOT (N)
    CB = N ^ (1 / 3)
    CBROOT = CB
END FUNCTION
