REM 'program using FUNCTION……END FUNCTION to find the area and perimeter of square
DECLARE FUNCTION AREA (L)
DECLARE FUNCTION PERIMETER (L)
CLS
INPUT "ENTER LENGTH"; L
PRINT "AREA OF SQUARE "; AREA(L)
PRINT "PERIMETER OF RECTANGLE "; PERIMETER(L)
END

FUNCTION AREA (L)
    AREA = L ^ 2
END FUNCTION

FUNCTION PERIMETER (L)
    PERIMETER = 4 * L
END FUNCTION
