REM 'to calculate profit percentage using function procedure.
DECLARE FUNCTION PROFITP (CP, SP)
CLS
INPUT "ENTER COST PRICE"; CP
INPUT "ENTER SELLING PRICE"; SP
PRINT "PROFIT PERCENTAGE="; PROFITP(CP, SP)
END

FUNCTION PROFITP (CP, SP)
    PP = ((SP - CP) / CP) * 100
    PROFITP = PP
END FUNCTION
